
LOGO = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/LOGO.png"
DS4A = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/ds4a.jpg"
ALEJANDRO = "assets/img/Alejandro.jpeg"
DANIEL = "assets/img/Daniel.jpeg"
AUGUSTO = "assets/img/Augusto.jpeg"
CARLOS = "assets/img/Carlos.jpeg"
JOSE = "assets/img/Jose.jpeg"
ALEJANDRA = "assets/img/Alejandra.jpeg"
MARIA = "assets/img/Maria.jpeg"