
LOGO = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/LOGO.png"
DS4A = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/ds4a.jpg"
ALEJANDRO = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Alejandro.jpeg"
DANIEL = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Daniel.jpeg"
AUGUSTO = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Augusto.jpeg"
CARLOS = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Carlos.jpeg"
JOSE = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Jose.jpeg"
ALEJANDRA = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Alejandra.jpeg"
MARIA = "https://raw.githubusercontent.com/cosmolejo/ds4a_dash/main/assets/img/Maria.jpeg"
